[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
startCommand = "gunicorn flightcode.wsgi:application --bind 0.0.0.0:$PORT"

[environment]
DJANGO_SETTINGS_MODULE = "flightcode.settings"
DEBUG = "False"
SECRET_KEY = "change-this-in-production"