# Generated by Django 5.2.6 on 2025-09-25 19:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PassengerEcoScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, unique=True)),
                ('points', models.IntegerField(default=0)),
                ('badges', models.TextField(blank=True, help_text='Comma-separated list of badges')),
            ],
            options={
                'ordering': ['-points'],
            },
        ),
        migrations.CreateModel(
            name='FlightRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('distance_km', models.FloatField()),
                ('aircraft_type', models.CharField(max_length=50)),
                ('fuel_burn_per_km', models.FloatField(help_text='Fuel consumption in liters per km')),
            ],
            options={
                'unique_together': {('origin', 'destination', 'aircraft_type')},
            },
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co2_kg', models.FloatField(help_text='CO2 emissions in kilograms')),
                ('fuel_saved_liters', models.FloatField(default=0.0, help_text='Fuel saved in liters')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='optimiser.flightroute')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
